name: Run Tests

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: ${{ github.event.label.name == 'actions:release' }}
    steps:
    - name: Run tests
      run: echo running tests