name: Release

on:
  push:
   tags:
      - '**'

jobs:
  build-test:
    name: Generate Version Badge
    runs-on: ubuntu-24.04
    steps:
    - name: Setup
      run: |
        mkdir -p ./build
        echo "Version: ${{ github.ref_name }}"
        # echo "Version: ${{ github.ref_name }}" > build/version.txt

    - name: Create Badge
      uses: jaywcjlove/generated-badges@main
      with:
        label: version
        status: ${{ github.ref_name }}
        output: ./build/badge-version.svg

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./build
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'