name: "PHPUnit"

on:
  push:
    branches-ignore: [ master, develop ]

jobs:
  phpunit:
    name: "PHPUnit"
    env:
      CODE_COVERAGE: none
      LC_ALL: en_US.UTF-8
      PHP_EXTENSIONS: mbstring, xml, ctype, iconv
      PHP_TOOLS: "composer:v2"
      PHP_VERSION: "8.4"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout ${{ github.repository }}"
        uses: "actions/checkout@v4"

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          args: --no-interaction --no-progress --no-suggest
          dev: yes
          php_extensions: ${{ env.PHP_EXTENSIONS }}
          php_version: ${{ env.PHP_VERSION }}

      - name: Run unit test
        uses: php-actions/phpunit@v3
        with:
          args: "--log-junit phpunit-report.xml"
          configuration: phpunit.xml
          php_extensions: ${{ env.PHP_EXTENSIONS }}
          php_version: ${{ env.PHP_VERSION }}
          memory_limit: 1G
          testsuite: unit
          version: latest

      - name: Test Summary
        if: env.CODE_COVERAGE != 'none'
        uses: test-summary/action@v2
        with:
          paths: phpunit-report*.xml
