name: "PHPUnit"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    name: "PHPUnit"
    env:
      LC_ALL: en_US.UTF-8
      CODE_COVERAGE: n
    continue-on-error: ${{ matrix.php-version == '8.3' }}

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        dependencies:
          - "locked"
        operating-system:
          - "ubuntu-latest"
        composer:
          - "composer:v2"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: mbstring, xml, ctype, iconv
          tools: ${{matrix.composer}}

      - name: "Install dependencies"
        run: |
          composer update --no-interaction --no-progress

      - name: "Unit Tests"
        run: composer test-linux
