name: "PHPUnit"

on:
  push:
    branches-ignore: [ master, develop ]

jobs:
  Action-Linting:
    name: Lint Basics
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: devops-actions/actionlint@v0.1.2
      - run: "composer validate --strict"

  phpunit:
    name: "PHPUnit"
    env:
      CODE_COVERAGE: none
      LC_ALL: en_US.UTF-8
      PHP_EXTENSIONS: mbstring, xml, ctype, iconv
      PHP_TOOLS: "composer:v2"
      PHP_VERSION: "8.2"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout ${{ github.repository }}"
        uses: "actions/checkout@v4"

      - name: Restore cached dependencies
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-${{ env.PHP_VERSION }}-composer-${{ hashFiles('**/composer.lock') }}
          path: |
            ./vendor

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          args: --no-suggest
          dev: yes
          interaction: no
          php_extensions: ${{ env.PHP_EXTENSIONS }}
          php_version: ${{ env.PHP_VERSION }}
          progress: yes

      - name: Cache Composer dependencies
        id: cache-composer-dependencies
        if: always() && steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
          path: ./vendor

      - name: Run unit test
        uses: php-actions/phpunit@v3
        with:
          args: "--log-junit phpunit-report.xml"
          configuration: phpunit.xml
          php_extensions: ${{ env.PHP_EXTENSIONS }}
          php_version: ${{ env.PHP_VERSION }}
          memory_limit: 1G
          testsuite: unit
          version: latest
