name: "PHPUnit"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    name: "PHPUnit"
    env:
      LC_ALL: en_US.UTF-8
      CODE_COVERAGE: none
    continue-on-error: ${{ matrix.php-version == '8.3' }}

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
        dependencies:
          - "locked"
        operating-system:
          - "ubuntu-latest"
        composer:
          - "composer:v2"
        include:
          # - php-version: 8.3
          #   operating-system: "ubuntu-latest"
          #   dependencies: "lowest"
          - php-version: 8.3
            operating-system: "ubuntu-latest"
            dependencies: "highest"

    steps:
      - name: Enable code coverage
        if: matrix.php-version == '8.3' && startsWith(matrix.operating-system, 'ubuntu') && matrix.dependencies == 'locked'
        run: printf 'CODE_COVERAGE=pcov\n' >> "$GITHUB_ENV"

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: mbstring, xml, ctype, iconv
          coverage: ${{ env.CODE_COVERAGE }}
          tools: ${{matrix.composer}}

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: |
          composer update --prefer-lowest --no-interaction --no-progress --no-suggest

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: |
          composer update --no-interaction --no-progress --no-suggest
  
      - name: "Install locked dependencies"
        if: ${{ matrix.dependencies == 'locked' }}
        run: |
          composer install --no-interaction --no-progress --no-suggest

      - name: "Perform unit tests"
        run: composer test-unit

      - name: "Perform unit tests with coverage"
        if: env.CODE_COVERAGE != 'none'
        run: |
          php ./vendor/bin/phpunit --configuration ./tests/phpunit-cc.xml --coverage-clover=clover.xml --testsuite Unit

      - name: "Remove .gitignore to make coverage badge working"
        if: env.CODE_COVERAGE != 'none'
        run: |
          rm .gitignore

      - name: Make code coverage badge
        if: env.CODE_COVERAGE != 'none'
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: doc/images/coverage.svg
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        
      # - name: Git push to image-data branch
      #   if: env.CODE_COVERAGE != 'none' && github.event_name == 'pull_request'
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_dir: ./output
      #     publish_branch: image-data
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     user_name: 'github-actions[bot]'
      #     user_email: 'github-actions[bot]@users.noreply.github.com'
