name: "PHPUnit"

on:
  push:
    branches-ignore: [ master, develop ]

jobs:
  phpunit:
    name: "PHPUnit"
    env:
      CODE_COVERAGE: none
      LC_ALL: en_US.UTF-8
      PHP_EXTENSIONS: mbstring, xml, ctype, iconv
      PHP_TOOLS: "composer:v2"
      PHP_VERSION: "8.4"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout ${{ github.repository }}"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: ${{ env.CODE_COVERAGE }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          php-version: ${{ env.PHP_VERSION }}
          tools: ${{ env.PHP_TOOLS }}

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --strict"

      # - name: Get Composer Cache Directory
      #   id: composer-cache
      #   run: |
      #     "echo \"COMPOSER_CACHE_DIR=$(composer config cache-dir --working-dir=.)\" >> $GITHUB_ENV"

      - uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: "Install locked dependencies"
        run: |
          "composer install --no-interaction --no-progress --no-suggest"

      - name: "Perform unit tests"
        run: |
          "./vendor/bin/phpunit --configuration ./phpunit.xml --log-junit phpunit-report.xml --testsuite Unit"

      - name: Test Summary
        if: env.CODE_COVERAGE != 'none'
        uses: test-summary/action@v2
        with:
          paths: phpunit-report*.xml
